### ISSUE TITLE
Header Should be sticky.

### ISSUE THREAD

**Issue by gsetia402** [paetztm/recycler_view_headers#3]
Hi, Header and Footer both perfectly attached to recycler view. But according to article Header should stick on the top of the screen and so as Footer in the bottom.
Please Navigate us to do so.

Thanks

**Comment by paetztm** [comment]
Hey,

I'm unclear what you are asking and what the problem is.  Can you share a screen shot of the problem and code?

Thanks

**Comment by gsetia402** [comment]
Hi,
Thanks for the response, I want a screen like an app 'swiggy'.
On this screen, the centre part in the attached image, (77 restaurants,
relevance) part will be stick on the top when you scroll up.
It would be a great help if we can talk over phone. Feel free to call
anytime.

Thanks
Gaurav Setia
8920895002

**Comment by paetztm** [comment]
Hey Guarav,

Can you attach the image to the github issue rather than emailing it?  I also have no idea what a swiggy is...

Thanks
