### ISSUE TITLE
ScrollView

### ISSUE THREAD

**Issue by muskan0048** [paetztm/recycler_view_headers#5]
when I put recyclerview in scroll view the sticky headers dont work

**Comment by paetztm** [comment]
Do you have a sample app with code?

**Comment by muskan0048** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">



    <android.support.v7.widget.Toolbar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:background="@color/white"
        android:elevation="0dp"
        android:layout_height="56dp"
        />

    <ScrollView
        android:id="@+id/helo"
        android:background="@color/white"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/toolbar">
        <RelativeLayout
            android:layout_width="match_parent"

            android:layout_height="wrap_content">
    <LinearLayout
        android:id="@+id/gap"
        android:layout_width="wrap_content"
        android:descendantFocusability="blocksDescendants"
        android:layout_height="68dp">

        <ImageView
            android:id="@+id/imagelogo"

            android:layout_width="59dp"
            android:layout_height="50dp"
            android:layout_marginLeft="@dimen/_5sdp"
            android:background="@drawable/roundimage"
            />


        <TextView
            android:id="@+id/titleee"
            android:layout_width="303dp"
            android:layout_height="40dp"
            android:layout_marginLeft="@dimen/_15sdp"
            android:background="@color/white"

            android:fontFamily="@font/montserrat"
            android:paddingLeft="@dimen/_4sdp"
            android:text="Name"
            android:textAllCaps="false"
            android:textColor="@color/nexttoblack"
            android:textSize="@dimen/_18sdp"
            />
    </LinearLayout>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycle2"
                android:layout_below="@id/gap"

                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/_15sdp"
                android:layout_gravity="center"
                android:layout_marginBottom="10sp"
                app:layout_behavior="@string/appbar_scrolling_view_behavior"
                android:background="@color/white"
                />

        </RelativeLayout>
    </ScrollView>


    <TableRow
        android:id="@+id/hr"
        android:layout_width="match_parent"
        android:layout_height="1sp"
        android:layout_alignParentStart="true"
        android:layout_alignTop="@+id/helo"
        android:background="#07000000">

    </TableRow>

    <RelativeLayout
        android:id="@+id/relt"
        android:layout_width="139dp"
        android:layout_height="49dp"
        android:layout_gravity="bottom|center_horizontal">

        <Button
            android:id="@+id/fab"
            android:layout_width="101dp"
            android:layout_height="28dp"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:layout_marginStart="19dp"
            android:layout_marginTop="13dp"
            android:background="@drawable/bca"
            android:clickable="true"
            android:elevation="40dp"
            android:fontFamily="@font/foodname"
            android:paddingLeft="13sp"
            android:src="@drawable/menu"
            android:text="Menu"
            android:textColor="@color/bll"
            android:textAlignment="textStart"
             />

        <ImageView
            android:layout_width="33dp"
            android:layout_height="22dp"
            android:layout_alignParentEnd="true"
            android:layout_centerVertical="true"
            android:layout_marginEnd="26dp"
            android:paddingTop="5sp"
            android:elevation="10dp"
            android:src="@drawable/fork" />


    </RelativeLayout>

    <TextView
        android:id="@+id/textView19"
        android:layout_width="138dp"
        android:layout_height="30dp"
        android:layout_gravity="bottom|right"
        android:layout_marginBottom="25sp"
        android:layout_marginRight="20sp"
        android:elevation="30dp"
        android:fontFamily="@font/montserrat"
        android:text="View Cart -->"
        android:textColor="@color/white"
        android:textSize="16sp"
        android:visibility="invisible" />
</RelativeLayout>

**Comment by paetztm** [comment]
If you want support, you're going to have to provide a complete app where I can press one button on Android Studio and it shows the problem you are facing.  What you provided above isn't nearly enough.
